# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Kaptain contributors (Fred Cooke)

name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  basic-quality:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/basic-quality-checks.yaml@1.0.1
    with:
      block-slashes: true
